# you can just use 'git' if it's in your PATH
git install: C:\Program Files\Git\cmd\git.exe

java:
  repo: D:\Minecraft\Java Storage\History
  # new versions will be downloaded to the first folder listed here
  # I use another folder for archived versions so the launcher isn't slowed down
  version folders:
  - '%appdata%\.minecraft\versions'
  - '%appdata%\.minecraft\versions\~ARCHIVE'
  assets folder: '%appdata%\.minecraft\assets'
  mcp:
    merged: D:\Minecraft\Java Storage\MCP\Merged
    matched: 1.14.4
  # Minecraft builtin java, seems to work well
  java install:
  - C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-gamma\windows-x64\java-runtime-gamma\bin\java.exe
  - java
  # I got fernflower from https://github.com/hube12/DecompilerMC/blob/master/lib/fernflower.jar 
  fernflower jar: forgeflower.jar
  # I got cfr from https://github.com/leibnitz27/cfr/releases
  cfr jar: cfr-0.152.jar
  # I got specialsource from https://ci.md-5.net/job/SpecialSource/148/
  special source jar: SpecialSource-1.10.0-shaded.jar
  # folder to store downloaded server jars
  server jars: D:\Minecraft\Java Storage\Server Jars
  # choose 'cfr' or 'fernflower'
  decompiler: cfr
  # arguments passed to java when invoking the decompiler
  decompiler args: -Xmx2400M -Xms600M
  # arguments passed to the decompiler itself
  cfr args: --caseinsensitivefs true --comments false --showversion false --sealed true
  fernflower args: -hes=0 -hdc=0 -dgs=1 -log=WARN
  # versions newer than this date will extract data reports
  data generators: 2018-01-01
  # exclude stuff except the vanilla data/resource packs
  jar exclude:
  - \.class$
  - \.xml$
  - ^META-INF/
  # exclude non-mojang libraries
  decompile exclude:
  - ^oshi/
  - ^org/
  - ^META-INF/
  - ^joptsimple/
  - ^javax/
  - ^it/unimi/
  - ^io/netty/
  - ^com/sun/
  - ^com/google/
  - ^gnu/trove/
  nbt translations:
  - extension: nbt
    remove keys: [DataVersion]
    endian: big
    structure: true
  # these files change constantly due to hash order, so sort them to prevent unneeded diffs
  json sorting:
  - file:
    - jar/data/minecraft/advancements/nether/all_effects.json
    - jar/data/minecraft/advancements/nether/all_potions.json
    sort:
      path: [criteria, all_effects, conditions, effects]
  - file:
    - jar/data/minecraft/loot_tables/chests/shipwreck_supply.json
    - jar/data/minecraft/loot_tables/chests/ancient_city_ice_box.json
    sort:
      path: [pools, {}, entries, {name: "minecraft:suspicious_stew"}, functions, {function: "minecraft:set_stew_effect"}, effects]
      by: [type]
      pick: value
  - file: reports/biome_parameters
    sort:
    - path: [biomes, {}]
      order: [biome, parameters]
    - path: [biomes, {}, parameters]
    - path: [biomes, {}, parameters]
      order: [depth, offset]
  - file:
    - reports/worldgen/minecraft/worldgen/noise_settings
    - reports/minecraft/worldgen/noise_settings
    - jar/data/minecraft/worldgen/noise_settings
    sort:
    - path: [structures, structures]
    - path: [structures]
  - file:
    - reports/worldgen/minecraft/worldgen/configured_structure_feature
    - reports/minecraft/worldgen/configured_structure_feature
    - jar/data/minecraft/worldgen/configured_structure_feature
    sort:
      path: [spawn_overrides]
  - file:
    - reports/worldgen/minecraft/worldgen/world_preset
    - reports/minecraft/worldgen/world_preset
    - jar/data/minecraft/worldgen/world_preset
    sort:
      path: [dimensions]
      order: ['minecraft:overworld', 'minecraft:the_nether', 'minecraft:the_end']
  - file:
    - reports/worldgen/minecraft/worldgen/flat_level_generator_preset
    - reports/minecraft/worldgen/flat_level_generator_preset
    - jar/data/minecraft/worldgen/flat_level_generator_preset
    sort:
      path: [settings, structure_overrides]
  - file:
    - reports/worldgen/minecraft/worldgen/structure
    - reports/minecraft/worldgen/structure
    - jar/data/minecraft/worldgen/structure
    sort:
    - path: []
      order: [type, biomes, step, start_pool, size, max_distance_from_center, project_start_to_heightmap, start_height, use_expansion_hack, adapt_noise, terrain_adaptation, mineshaft_type, is_beached, biome_temp, large_probability, cluster_probability, height, setups, spawn_overrides, value]
    - path: [value]
      order: [biomes, step, start_pool, size, max_distance_from_center, project_start_to_heightmap, start_height, use_expansion_hack, adapt_noise, terrain_adaptation, spawn_overrides]
    - path: [spawn_overrides]
    - path: [value, spawn_overrides]
  - file:
    - reports/worldgen/minecraft/dimension_type
    - reports/minecraft/dimension_type
    - jar/data/minecraft/dimension_type
    sort:
    - path: []
  - file:
    - reports/worldgen/minecraft/worldgen
    - reports/minecraft/worldgen
    - jar/data/minecraft/worldgen
    sort:
    - up_path: []
      matches: {}
    - up_path: []
      matches: {}
      order: [type, min, max, min_inclusive, max_inclusive, minCount, maxCount, min_dist, max_dist, min_chance, max_chance, min_threshold, max_threshold, min_delay, max_delay, min_gen_offset, max_gen_offset]
  - file: reports/commands.json
    sort:
    - up_path: ['*', children]
      order: [type, parser, properties, executable, redirect, children]
    - up_path: []
      matches: properties
      order: [type, amount, min, max]
    - up_path: []
      matches: children
  - file: reports/blocks.json
    require:
      after: 2022-05-04
    sort:
    - path: []
      by: ["states", 0, "id"]
      pick: value
    - path: ['*', states, {}]
      order: [properties, id, default]
    - path: ['minecraft:piston_head', properties]
      order: [facing, short, type]
    - path: ['minecraft:piston_head', states, {}, properties]
      order: [facing, short, type]
    - path: ['minecraft:moving_piston', properties]
      order: [facing, type]
    - path: ['minecraft:moving_piston', states, {}, properties]
      order: [facing, type]
    - path: ['minecraft:chest', properties]
      order: [facing, type, waterlogged]
    - path: ['minecraft:chest', states, {}, properties]
      order: [facing, type, waterlogged]
    - path: ['minecraft:trapped_chest', properties]
      order: [facing, type, waterlogged]
    - path: ['minecraft:trapped_chest', states, {}, properties]
      order: [facing, type, waterlogged]
  - file: reports/registries.json
    sort:
    - path: []
      by: ["protocol_id"]
      pick: value
    - path: ['*', entries]
      by: ["protocol_id"]
      pick: value
    - path: ['*']
      order: [default, protocol_id, entries]
    # 14w06a added models to the jar
    # 20w10a started to generate them with code
    # 22w18a alphabetized them
  - file: jar/assets/minecraft/models
    require:
      after: 2020-03-04
      seems_generated: true
    sort:
    - path: [textures]
    - path: [textures]
      order: [texture, all, particle, top, bottom, side, end, up, down, north, south, east, west]
    # 17w13a added advancements to the jar
    # 17w43a moved them from assets to data
    # 18w09a started to generated them with code
    # 22w18a alphabetized them
  - file: jar/data/minecraft/advancements
    sort:
    - path: []
      order: [parent, display, rewards, criteria, requirements]
    - path: [display]
      order: [icon, title, description, frame, show_toast, announce_to_chat, hidden]
    - path: [criteria, '*']
      order: [trigger, conditions]
    - path: [criteria]
    - path: [criteria]
      order: [has_the_recipe]
      after: true
    - path: [requirements, '*']
    - path: [requirements, '*']
      order: [has_the_recipe]
      after: true
    - path: [requirements]
      by: [0]
      pick: value
    - path: [criteria, '*', conditions]
      order: [signal_strength, projectile, start_position, distance, item, player, entity, lightning, bystander, location, parent, partner, child, block, num_bees_inside]
    - up_path: []
      matches: {"condition":"minecraft:entity_properties"}
      order: [condition, entity, predicate]
    - up_path: []
      matches: type_specific
      order: [type, size, variant, in_open_water, blocks_set_on_fire, entity_struck, gamemode, level, looking_at, recipes, stats, advancements]
    - up_path: []
      matches: killing_blow
      order: [is_explosion, is_fire, is_magic, is_projectile, is_lightning, bypasses_armor, bypasses_invulnerability, bypasses_magic, direct_entity, source_entity]
    - up_path: [damage]
      matches: type
      order: [is_explosion, is_fire, is_magic, is_projectile, is_lightning, bypasses_armor, bypasses_invulnerability, bypasses_magic, direct_entity, source_entity]
    - up_path: []
      matches: damage
      order: [dealt, taken, blocked, type, source_entity]
    - up_path: []
      matches: predicate
      order: [type, team, nbt, flags, distance, type_specific, passenger, vehicle, targeted_entity, equipment, effects, location, stepping_on]
    - up_path: []
      matches: location
      order: [position, smokey, biome, dimension, feature, block, fluid, light]
    # 15w43a added loot tables to the jar
    # 17w43a moved them from assets to data
    # 18w43a started to generated them with code
    # 22w18a alphabetized them
  - file: jar/data/minecraft/loot_tables
    sort:
    - path: []
      order: [type, pools, functions]
    - path: [pools, {}]
      order: [rolls, bonus_rolls, entries, conditions, functions]
    - up_path: [{}, conditions]
      order: [condition, name, inverse, term, terms, offsetX, offsetY, offsetZ, raining, thundering, chance, looting_multiplier, value, period, range, enchantment, block, properties, entity, predicate, scores, chances]
    - up_path: [{}, functions]
      order: [function, conditions, append, enchantment, formula, parameters, source, ops, block, properties, enchantments, levels, treasure, destination, search_radius, skip_existing_chunks, decoration, zoom, entity, count, limit, modifiers, patterns, type, entries, damage, name, seed, lore, tag, id, effects, add]
    - up_path: [{}, ops]
      order: [source, target, op]
    - up_path: [{}, entries]
      order: [type, name, weight, quality, children, conditions, functions]
    - up_path: [{}, children]
      order: [type, name, weight, quality, children, conditions, functions]
    - up_path: []
      matches: {"type":"minecraft:uniform"}
      order: [type, min, max]
    - up_path: []
      matches: type_specific
      order: [type, size, variant, in_open_water, blocks_set_on_fire, entity_struck, gamemode, level, looking_at, recipes, stats, advancements]
    # 17w13a added recipes to the jar
    # 17w48a moved them from assets to data
    # 22w18a alphabetized them
  - file: jar/data/minecraft/recipes
    sort:
    - path: []
      order: [type, group, pattern, key, ingredients, ingredient, base, addition, result, count, experience, cookingtime]
    - path: [result]
      order: [item, count]
    - path: [key]
  - file: jar/assets/minecraft/blockstates
    require:
      after: 2020-03-04
    sort:
    - path: [variants, '*', {}]
      order: [model, x, y, z, uvlock, weight]
    - path: [variants, '*']
      order: [model, x, y, z, uvlock, weight]
    - path: [multipart, {}]
      order: [when, apply]
    - path: [multipart, {}, apply]
      order: [model, x, y, z, uvlock, weight]
    - path: [multipart, {}, apply, {}]
      order: [model, x, y, z, uvlock, weight]
    - path: [multipart, {}, when, OR, {}]
    - path: [multipart, {}, when]
  version facts:
    skip:
    - (?i)optifine
    - ^a1\.0\.6$ # can't unzip
    ordering:
      priority:
      - listed order
      - release time
      - best guess
      # some versions have a low-precision or completely wrong release time, so we need to manually say the order
      versions:
      - c0.0.11a
      - c0.0.12a_03
      - c0.0.13a
      - c0.0.13a_03
      - c0.0.14a_08
      - c0.0.15a-1
      - c0.0.16a_02
      - c0.0.17a
      - c0.0.18a_02
      - c0.0.19a_06-2
      - c0.0.20a_01
      - c0.0.21a
      - c0.0.22a_05
      - c0.0.23a_01
      - a1.1.0
      - a1.1.0-1
      - a1.1.0-2
      - 1.0.0-rc1
      - 1.0.0-rc2-1
      - 1.0.0-rc2-2
      - 1.0.0-rc2-3
      - 12w30c
      - 1.3
      - 1.4.3
      - 1.4.4
      - 1.4.5
      - 12w49a
      - 12w50a
      - 12w50b
      - 1.4.6
      - 13w07a
      - 13w09a
      - 13w09b
      - 13w09c
      - 13w10a
      - 13w10b
      - 13w11a
    insane:
      # prevent the history guesser from parenting versions to these
      releases:
      - April Fools
      - Combat Test
      versions: []
    parents:
      1.18_experimental-snapshot-1: 1.17.1-pre1
      1.19_deep_dark_experimental_snapshot-1: 1.18.1
      22w13oneblockatatime: 1.18.2
    releases:
      regex:
        ^2\.0-blue$: April Fools 2013 (Blue)
        ^2\.0-red$: April Fools 2013 (Red)
        ^2\.0-purple$: April Fools 2013 (Purple)
        ^15w14a$: April Fools 2015
        ^1\.RV-Pre1$: April Fools 2016
        ^3D Shareware v1\.34$: April Fools 2019
        ^20w14infinite$: April Fools 2020
        ^22w13oneblockatatime$: April Fools 2022
        ^1\.14_combat-212796$: Combat Test 1
        ^1\.14_combat-\d$: Combat Test 2
        ^1\.15_combat-1$: Combat Test 3
        ^1\.15_combat-6$: Combat Test 4
        ^1\.16_combat-\d$: Combat Test 5
        ^1\.18_experimental-snapshot-(\d+)$: 1.18
        ^1\.19_deep_dark_experimental-snapshot-(\d+)$: 1.19
        ^rd-.+$: Pre-Classic
        ^c0\..+$: Classic
        ^in-.+$: Indev
        ^inf-.+$: Infdev
        ^a(\d+\.\d+).*$: Alpha $1
        ^b(\d+\.\d+).*$: Beta $1
        ^(\d+\.\d+).*$: $1
      # this needs to be updated whenever a new version comes out,
      # or the program will think new snapshots are for old versions
      # in the future, it will probably be smart enough to guess that isn't the case
      snapshots:
      - {year: 2011, release: 1.1}
      - {year: 2012, weeks: [1,1], release: 1.1}
      - {year: 2012, weeks: [3,8], release: 1.2}
      - {year: 2012, weeks: [15,30], release: 1.3}
      - {year: 2012, weeks: [32,50], release: 1.4}
      - {year: 2013, weeks: [1,12], release: 1.5}
      - {year: 2013, weeks: [16,26], release: 1.6}
      - {year: 2013, weeks: [36,49], release: 1.7}
      - {year: 2014, weeks: [2,34], release: 1.8}
      - {year: 2015, weeks: [31,51], release: 1.9}
      - {year: 2016, weeks: [2,15], release: 1.9}
      - {year: 2016, weeks: [20,21], release: 1.10}
      - {year: 2016, weeks: [32,50], release: 1.11}
      - {year: 2017, weeks: [6,31], release: 1.12}
      - {year: 2017, weeks: [43,50], release: 1.13}
      - {year: 2018, weeks: [1,33], release: 1.13}
      - {year: 2018, weeks: [43,50], release: 1.14}
      - {year: 2019, weeks: [2,14], release: 1.14}
      - {year: 2019, weeks: [34,46], release: 1.15}
      - {year: 2020, weeks: [6,30], release: 1.16}
      - {year: 2020, weeks: [45,51], release: 1.17}
      - {year: 2021, weeks: [3,36], release: 1.17}
      - {year: 2021, weeks: [37,44], release: 1.18}
      - {year: 2022, weeks: [3,10], release: 1.18}
      - {year: 2022, weeks: [11,44], release: 1.19}

bedrock:
  repo: D:\Minecraft\Bedrock Storage\History
  version folders:
  - D:\Minecraft\Bedrock Storage\Builds
  - D:\Minecraft\Bedrock Storage\Builds\~ARCHIVE
  nbt translations:
  - extension: mcstructure
    endian: little
  - extension: nbt
    endian: big
    structure: true
  pack merging:
    behavior:
      layers:
      - vanilla
      - vanilla_gametest
      - vanilla_1.14
      - vanilla_1.15
      - vanilla_1.16
      - vanilla_1.16.100
      - vanilla_1.16.200
      - vanilla_1.16.210
      - vanilla_1.16.220
      - vanilla_1.17.0
      - vanilla_1.17.10
      - vanilla_1.17.20
      - vanilla_1.17.30
      - vanilla_1.17.40
      - vanilla_1.18.0
      - vanilla_1.18.10
      - vanilla_1.18.20
      - vanilla_1.18.30
      - vanilla_1.19.0
      - vanilla_1.19.10
      - vanilla_1.19.20
      - vanilla_1.19.30
      - vanilla_1.19.40
      - vanilla_1.19.50
      - experimental_vanilla_experiments_internal
      - experimental_vanilla_experiments
      - experimental_caves_and_cliffs_internal
      - experimental_caves_and_cliffs
      - experimental_wild_update_internal
      - experimental_wild_update
      - experimental_spectator_internal
      - experimental_next_major_update
      merging:
      - path: contents.json
        operation: append_list
        list: [content]
      - path: manifest.json
        operation: no_merge
    resource:
      layers:
      - vanilla
      - vanilla_base
      - vanilla_music
      - vanilla_1.14
      - vanilla_1.15
      - vanilla_1.16
      - vanilla_1.16.100
      - vanilla_1.16.200
      - vanilla_1.16.210
      - vanilla_1.16.220
      - vanilla_1.17.0
      - vanilla_1.17.10
      - vanilla_1.17.20
      - vanilla_1.17.30
      - vanilla_1.17.40
      - vanilla_1.18.0
      - vanilla_1.18.10
      - vanilla_1.18.20
      - vanilla_1.18.30
      - vanilla_1.19.0
      - vanilla_1.19.10
      - vanilla_1.19.20
      - vanilla_1.19.30
      - vanilla_1.19.40
      - vanilla_1.19.50
      - experimental_vanilla_experiments_internal
      - experimental_vanilla_experiments
      - experimental_caves_and_cliffs_internal
      - experimental_caves_and_cliffs
      - experimental_wild_update_internal
      - experimental_wild_update
      - experimental_spectator_internal
      - experimental_next_major_update
      merging:
      - path: biomes_client.json
      - path: blocks.json
      - path: sounds.json
      - path: splashes.json
      - path: entity
      - path: materials/entity.material
      - path: textures/item_texture.json
      - path: textures/terrain_texture.json
      - path: textures/textures_list.json
      - path: textures/flipbook_textures.json
      - path: sounds/music_definitions.json
      - path: sounds/sound_definitions.json
        move_keys:
          from: ['@(?!^format_version$)(?!^sound_definitions$)(^.*$)']
          to: ['sound_definitions']
      - extension: lang
        operation: append_lines
      - path: contents.json
        operation: append_list
        list: [content]
      - path: textures/textures_list.json
        operation: append_list
        list: []
      - path: manifest.json
        operation: no_merge
  version facts:
    insane:
      releases:
      - Editor Tests
    skip:
    - 1.1.0.0
    - 1.7.5.0
    ordering:
      priority:
      - listed order
      - release time
      - best guess
      versions:
      - 1.16.22002.0
      - 1.16.22101.0
      - 1.16.23050.0
      - 1.16.23052.0
      - 1.16.23054.0
      - 1.16.23056.0
      - 1.17.50.0
      - 1.17.2.0
      - 1.17.1020.0
      - 1.17.1023.0
      - 1.17.1101.0
      - 1.17.2023.0
      - 1.17.3020.0
      - 1.17.3021.0
    parents:
      1.18.102.0: 1.18.2.0
      1.18.100.0: 1.18.1021.0
      1.18.1023.0: 1.18.1022.0
      1.18.2021.0: 1.18.1028.0
      1.18.3020.0: 1.18.2029.0
      1.18.3104.0: 1.18.3004.0
      1.19.1020.0: 1.19.5.0
      1.19.2101.0: 1.19.2002.0
      1.19.4020.0: 1.19.3023.0
      1.19.3101.0: 1.19.3004.0
      1.19.5021.0: 1.19.4024.0
    releases:
      regex:
        ^1\.18\.100\.0$: Editor Tests
        ^1\.18\.1023\.0$: Preview
        ^(\d+\.\d+)\.\d\d?\.0$: $1
        ^(\d+\.\d+\.\d)\d\d\.0$: $1
        ^(\d+\.\d+\.\d\d)\d\d?\d?\.0$: $1
