# you can just use 'git' if it's in your PATH
git install: C:\Program Files\Git\cmd\git.exe
# contents of .gitignore file when repo is created
gitignore: ""

java:
  repo: D:\Minecraft\Java Storage\History
  # new versions will be downloaded to the first folder listed here
  # I use another folder for archived versions so the launcher isn't slowed down
  version folders:
  - '%appdata%\.minecraft\versions'
  - '%appdata%\.minecraft\versions\~ARCHIVE'
  # Minecraft builtin java, seems to work well
  java install: C:\Program Files (x86)\Minecraft Launcher\runtime\java-runtime-alpha\windows-x64\java-runtime-alpha\bin\java.exe
  # I got fernflower from https://github.com/hube12/DecompilerMC/blob/master/lib/fernflower.jar 
  fernflower jar: forgeflower.jar
  # I got cfr from https://github.com/leibnitz27/cfr/releases
  cfr jar: cfr-0.151.jar
  # I got specialsource from https://github.com/hube12/DecompilerMC/blob/master/lib/SpecialSource-1.9.1.jar
  special source jar: SpecialSource-1.9.1.jar
  # folder to store downloaded server jars
  server jars: D:\Minecraft\Java Storage\Server Jars
  # choose 'cfr' or 'fernflower'
  decompiler: cfr
  # arguments passed to java when invoking the decompiler
  decompiler args: -Xmx2400M -Xms600M
  # arguments passed to the decompiler itself
  cfr args: --caseinsensitivefs true --comments false --showversion false
  fernflower args: -hes=0 -hdc=0 -dgs=1 -log=WARN
  # versions newer than this date will extract data reports
  data generators: 2018-01-01
  # exclude stuff except the vanilla data/resource packs
  jar exclude:
  - \.class$
  - \.xml$
  - ^META-INF/
  # exclude non-mojang libraries
  decompile exclude:
  - ^oshi/
  - ^org/
  - ^META-INF/
  - ^joptsimple/
  - ^javax/
  - ^it/unimi/
  - ^io/netty/
  - ^com/sun/
  - ^com/google/
  nbt translations:
  - extension: nbt
    remove keys: [DataVersion]
    endian: big
  # these files change constantly due to hash order, so sort them to prevent unneeded diffs
  json sorting:
    data/minecraft/advancements/nether/all_effects.json:
      path: [criteria, all_effects, conditions, effects]
      operation: sort_keys
    data/minecraft/advancements/nether/all_potions.json:
      path: [criteria, all_effects, conditions, effects]
      operation: sort_keys
    data/minecraft/loot_tables/chests/shipwreck_supply.json:
      path: [pools, {}, entries, {name: "minecraft:suspicious_stew"}, functions, {function: "minecraft:set_stew_effect"}, effects]
      operation: sort_by
      by: type
    # this functionality was removed and hasn't been readded yet, so commented out for now
    #assets/minecraft/blockstates:
    #- path: [variants, {}]
    #  order: [model, x, y, z, uvlock, weight]
  version facts:
    skip:
    - (?i)optifine
    - ^a1\.0\.6$ # can't unzip
    ordering:
      releases:
      # some versions have a low-precision release time, so we need to manually say the order
      # in the future, the program will be smarter and guess really obvious ones
      versions:
      - c0.0.11a
      - c0.0.12a_03
      - c0.0.13a
      - c0.0.13a_03
      - c0.0.14a_08
      - c0.0.15a-1
      - c0.0.16a_02
      - c0.0.17a
      - c0.0.18a_02
      - c0.0.19a_06-2
      - c0.0.20a_01
      - c0.0.21a
      - c0.0.22a_05
      - c0.0.23a_01
      - a1.1.0,
      - a1.1.0-1
      - a1.1.0-2
      - 1.0.0-rc1,
      - 1.0.0-rc2-1
      - 1.0.0-rc2-2
      - 1.0.0-rc2-3
      - 12w30c
      - 1.3
      - 1.4.3
      - 1.4.4
      - 1.4.5
      - 12w49a
      - 12w50a
      - 12w50b
      - 1.4.6
      - 13w07a
      - 13w09a
      - 13w09b
      - 13w09c
      - 13w10a
      - 13w10b
      - 13w11a
    insane:
      # prevent the history guesser from parenting versions to these
      releases:
      - April Fools
      - Combat Test
      versions:
    parents:
      1.18_experimental-snapshot-1: 1.17.1-pre1
    releases:
      regex:
        ^2\.0-blue$: April Fools 2013 (Blue)
        ^2\.0-red$: April Fools 2013 (Red)
        ^2\.0-purple$: April Fools 2013 (Purple)
        ^15w14a$: April Fools 2015
        ^1\.RV-Pre1$: April Fools 2016
        ^3D Shareware v1\.34$: April Fools 2019
        ^20w14infinite$: April Fools 2020
        ^1\.14_combat-212796$: Combat Test 1
        ^1\.14_combat-\d$: Combat Test 2
        ^1\.15_combat-1$: Combat Test 3
        ^1\.15_combat-6$: Combat Test 4
        ^1\.16_combat-\d$: Combat Test 5
        ^1\.18_experimental-snapshot-(\d+)$: 1.18
        ^rd-.+$: Pre-Classic
        ^c0\..+$: Classic
        ^in-.+$: Indev
        ^inf-.+$: Infdev
        ^a(\d+\.\d+).*$: Alpha $1
        ^b(\d+\.\d+).*$: Beta $1
        ^(\d+\.\d+).*$: $1
      # this needs to be updated whenever a new version comes out,
      # or the program will think new snapshots are for old versions
      # in the future, it will probably be smart enough to guess that isn't the case
      snapshots:
      - {year: 2011, release: 1.1}
      - {year: 2012, weeks: [1,1], release: 1.1}
      - {year: 2012, weeks: [3,8], release: 1.2}
      - {year: 2012, weeks: [15,30], release: 1.3}
      - {year: 2012, weeks: [32,50], release: 1.4}
      - {year: 2013, weeks: [1,12], release: 1.5}
      - {year: 2013, weeks: [16,26], release: 1.6}
      - {year: 2013, weeks: [36,49], release: 1.7}
      - {year: 2014, weeks: [2,34], release: 1.8}
      - {year: 2015, weeks: [31,51], release: 1.9}
      - {year: 2016, weeks: [2,15], release: 1.9}
      - {year: 2016, weeks: [20,21], release: 1.10}
      - {year: 2016, weeks: [32,50], release: 1.11}
      - {year: 2017, weeks: [6,31], release: 1.12}
      - {year: 2017, weeks: [43,50], release: 1.13}
      - {year: 2018, weeks: [1,33], release: 1.13}
      - {year: 2018, weeks: [43,50], release: 1.14}
      - {year: 2019, weeks: [2,14], release: 1.14}
      - {year: 2019, weeks: [34,46], release: 1.15}
      - {year: 2020, weeks: [6,30], release: 1.16}
      - {year: 2020, weeks: [45,51], release: 1.17}
      - {year: 2021, weeks: [3,36], release: 1.17}
      - {year: 2021, weeks: [37,999999999], release: 1.18}

bedrock:
  repo: D:\Minecraft\Bedrock Storage\History
  version folders:
  - D:\Minecraft\Bedrock Storage\Builds
  - D:\Minecraft\Bedrock Storage\Builds\~ARCHIVE
  nbt translations:
  - extension: mcstructure
    endian: little
  - extension: nbt
    endian: big
  pack merging:
    behavior:
      layers:
      - vanilla_gametest
      - vanilla
      - vanilla_1.14
      - vanilla_1.15
      - vanilla_1.16
      - vanilla_1.16.100
      - vanilla_1.16.200
      - vanilla_1.16.210
      - vanilla_1.16.220
      - vanilla_1.17.0
      - vanilla_1.17.10
      - vanilla_1.17.20
      - vanilla_1.17.30
      - vanilla_1.17.40
      - experimental_caves_and_cliffs
    resource:
      layers:
      - vanilla_base
      - vanilla
      - vanilla_music
      - vanilla_1.14
      - vanilla_1.15
      - vanilla_1.16
      - vanilla_1.16.100
      - vanilla_1.16.200
      - vanilla_1.16.210
      - vanilla_1.16.220
      - vanilla_1.17.0
      - vanilla_1.17.10
      - vanilla_1.17.20
      - vanilla_1.17.30
      - vanilla_1.17.40
      - experimental_caves_and_cliffs
      merging:
      - path: biomes_client.json
      - path: contents.json
      - path: splashes.json
      - path: textures/textures_list.json
      - path: textures/flipbook_textures.json
      - path: blocks.json
        overwrite: [format_version]
      - path: sounds.json
        overwrite: [volume, pitch]
      - path: textures/item_texture.json
        overwrite: [textures]
      - path: textures/terrain_texture.json
        overwrite: [textures]
      - path: sounds/sound_definitions.json
        overwrite: [volume, pitch, sounds]
      - path: sounds/music_definitions.json
        overwrite: [volume, pitch]
      - extension: lang
        operation: append_lines
  version facts:
    skip:
    - 1.1.0.0
    - 1.7.5.0
    ordering:
      versions:
      - 1.16.22002.0
      - 1.16.22101.0
      - 1.16.23050.0
      - 1.16.23052.0
      - 1.16.23054.0
      - 1.16.23056.0
      - 1.17.50.0
      - 1.17.2.0
      - 1.17.1020.0
      - 1.17.1023.0
      - 1.17.1101.0
      - 1.17.2023.0
      - 1.17.3020.0
      - 1.17.3021.0
    parents:
    releases:
      regex:
        ^(\d+\.\d+).*$: $1
